// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * The AddTime function adds milliseconds, seconds, minutes, hours or days to a Date and time, depending on the unitOfTime provided.
 * @param {Date} startDate
 * @param {Big} amount
 * @param {string} unitOfTime - Must be one of: "MILLISECOND"|"SECOND"|"MINUTE"|"HOUR"|"DAY"
 * @returns {Promise.<Date>}
 */
export async function AddTime(startDate, amount, unitOfTime) {
	// BEGIN USER CODE
    if (startDate == null) {
        throw new Error("Required field: startDate");
    }
    if (amount == null) {
        throw new Error("Required field: amount");
    }
    if (unitOfTime == null) {
        throw new Error("Required field: unitOfTime");
    }
    const n = amount.toNumber();
    switch (unitOfTime) {
        case "MILLISECOND":
            return new Date(startDate.getTime() + n * 1);
        case "SECOND":
            return new Date(startDate.getTime() + n * 1000);
        case "MINUTE":
            return new Date(startDate.getTime() + n * 60000);
        case "HOUR":
            return new Date(startDate.getTime() + n * 3600000);
        case "DAY":
            return new Date(startDate.getTime() + n * 86400000);
        default:
            throw new Error("Unit of time not supported: " + unitOfTime);
    }
	// END USER CODE
}
