import { watchPosition, unwatch } from 'react-native-nitro-geolocation';

// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * This action retrieves the current geographical position of a user/device with a minimum accuracy as parameter. If a position is not acquired with minimum accuracy within a specific timeout it will retrieve the last most precise location.
 *
 * Since this can compromise privacy, the position is not available unless the user approves it. The web browser will request the permission at the first time the location is requested. When denied by the user it will not prompt a second time.
 *
 * On hybrid and native platforms the permission should be requested with the `RequestLocationPermission` action.
 *
 * For good user experience, disable the nanoflow during action using property `Disabled during action` if you’re using `Call a nanoflow button` to run JS Action `Get current location with minimum accuracy`.
 *
 * Best practices:
 * https://developers.google.com/web/fundamentals/native-hardware/user-location/
 * @param {Big} timeout - The maximum length of time (in milliseconds) the device is allowed to take in order to return a location. If empty, there is no timeout.
 * @param {Big} maximumAge - The maximum age (in milliseconds) of a possible cached position that is acceptable to return. If set to 0, it means that the device cannot use a cached position and must attempt to retrieve the real current position. By default the device will always return a cached position regardless of its age.
 * @param {boolean} highAccuracy - Use a higher accuracy method to determine the current location. Setting this to false saves battery life.
 * @param {Big} minimumAccuracy - The minimum accuracy to be received in meters. Less amount of meters, more precise is the location.
 * @returns {Promise.<MxObject>}
 */
async function GetCurrentLocationMinimumAccuracy(timeout, maximumAge, highAccuracy, minimumAccuracy) {
    // BEGIN USER CODE
    const isReactNative = navigator && navigator.product === "ReactNative";
    const isWeb = navigator && navigator.geolocation;
    if (!isReactNative && !isWeb) {
        return Promise.reject(new Error("Geolocation module could not be found"));
    }
    return new Promise((resolve, reject) => {
        var _a;
        const options = buildLocationOptions(timeout, maximumAge, highAccuracy);
        let lastAccruedPosition;
        // Derive the watchdog timeout from the same clamped value used for the location layer,
        // so the two never disagree. `new Big(0)` is truthy, so we must not test `timeout`
        // directly here or a configured `0` would fire the watchdog on the next tick.
        const timeoutMs = (_a = options.timeout) !== null && _a !== undefined ? _a : 30000;
        const timeoutId = setTimeout(onTimeout, timeoutMs);
        let clearWatch;
        if (isReactNative) {
            const token = watchPosition(onSuccess, onError, options);
            clearWatch = () => unwatch(token);
        }
        else {
            // Workaround: browsers may ignore maximumAge on watchPosition unless getCurrentPosition is called first.
            // https://stackoverflow.com/questions/3397585/navigator-geolocation-getcurrentposition-sometimes-works-sometimes-doesnt
            navigator.geolocation.getCurrentPosition(() => { }, () => { }, {});
            const watchId = navigator.geolocation.watchPosition(pos => onSuccess(normalizeWebPosition(pos)), err => onError({ code: err.code, message: err.message }), {
                timeout: options.timeout,
                maximumAge: options.maximumAge,
                enableHighAccuracy: highAccuracy !== null && highAccuracy !== undefined ? highAccuracy : false
            });
            clearWatch = () => navigator.geolocation.clearWatch(watchId);
        }
        function onTimeout() {
            clearWatch();
            if (lastAccruedPosition) {
                createGeolocationObject(lastAccruedPosition);
            }
            else {
                reject(new Error("Timeout expired"));
            }
        }
        function onSuccess(position) {
            if (!minimumAccuracy || Number(minimumAccuracy) >= position.coords.accuracy) {
                clearTimeout(timeoutId);
                clearWatch();
                createGeolocationObject(position);
            }
            else {
                if (!lastAccruedPosition || position.coords.accuracy < lastAccruedPosition.coords.accuracy) {
                    lastAccruedPosition = position;
                }
            }
        }
        function onError(error) {
            clearTimeout(timeoutId);
            clearWatch();
            // Best effort within a timeout: if we already captured a usable (though not yet
            // minimum-accuracy) fix, return it instead of failing on a transient error such as
            // POSITION_UNAVAILABLE. Mirrors the onTimeout fallback.
            if (lastAccruedPosition) {
                createGeolocationObject(lastAccruedPosition);
            }
            else {
                reject(new Error(error.message));
            }
        }
        function createGeolocationObject(position) {
            mx.data.create({
                entity: "NanoflowCommons.Geolocation",
                callback: mxObject => resolve(mapPositionToMxObject(mxObject, position)),
                error: () => reject(new Error("Could not create 'NanoflowCommons.Geolocation' object to store location"))
            });
        }
    });
    function buildLocationOptions(timeout, maximumAge, highAccuracy) {
        let timeoutNumber = timeout ? timeout.toNumber() : undefined;
        const maximumAgeNumber = maximumAge ? maximumAge.toNumber() : undefined;
        // Normalize the timeout so the watchdog and the location layer always agree, on every platform:
        // - undefined (empty) -> 30 sec (default timeout)
        // - 0 -> 1 hour (treated as "no timeout")
        // A timeout of 0 or undefined also crashes on iOS, and on web `timeout: 0` means
        // "fail immediately with TIMEOUT" on every update, so it must never reach the location layer.
        if (timeoutNumber === undefined) {
            timeoutNumber = 30000;
        }
        else if (timeoutNumber === 0) {
            timeoutNumber = 3600000;
        }
        return {
            timeout: timeoutNumber,
            maximumAge: maximumAgeNumber,
            accuracy: highAccuracy ? { android: "high", ios: "best" } : { android: "balanced", ios: "hundredMeters" }
        };
    }
    // NOTE: `normalizeWebPosition` is duplicated verbatim in `GetCurrentLocation.ts`.
    // The Mendix action model does not allow sharing code across action files, so if you change this
    // function, keep the copy in the other action in sync.
    function normalizeWebPosition(pos) {
        var _a, _b, _c, _d;
        return {
            coords: {
                latitude: pos.coords.latitude,
                longitude: pos.coords.longitude,
                altitude: (_a = pos.coords.altitude) !== null && _a !== undefined ? _a : null,
                accuracy: pos.coords.accuracy,
                altitudeAccuracy: (_b = pos.coords.altitudeAccuracy) !== null && _b !== undefined ? _b : null,
                heading: (_c = pos.coords.heading) !== null && _c !== undefined ? _c : null,
                speed: (_d = pos.coords.speed) !== null && _d !== undefined ? _d : null
            },
            timestamp: pos.timestamp
        };
    }
    function mapPositionToMxObject(mxObject, pos) {
        mxObject.set("Timestamp", new Date(pos.timestamp));
        mxObject.set("Latitude", new Big(pos.coords.latitude.toFixed(8)));
        mxObject.set("Longitude", new Big(pos.coords.longitude.toFixed(8)));
        mxObject.set("Accuracy", new Big(pos.coords.accuracy.toFixed(8)));
        if (pos.coords.altitude != null) {
            mxObject.set("Altitude", new Big(pos.coords.altitude.toFixed(8)));
        }
        if (pos.coords.altitudeAccuracy != null && pos.coords.altitudeAccuracy !== -1) {
            mxObject.set("AltitudeAccuracy", new Big(pos.coords.altitudeAccuracy.toFixed(8)));
        }
        if (pos.coords.heading != null && pos.coords.heading !== -1) {
            mxObject.set("Heading", new Big(pos.coords.heading.toFixed(8)));
        }
        if (pos.coords.speed != null && pos.coords.speed !== -1) {
            mxObject.set("Speed", new Big(pos.coords.speed.toFixed(8)));
        }
        return mxObject;
    }
    // END USER CODE
}

export { GetCurrentLocationMinimumAccuracy };
