import { getCurrentPosition } from 'react-native-nitro-geolocation';

// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * This action retrieves the current geographical position of a user/device.
 *
 * Since this can compromise privacy, the position is not available unless the user approves it. The web browser will request the permission at the first time the location is requested. When denied by the user it will not prompt a second time.
 *
 * On hybrid and native platforms the permission should be requested with the `RequestLocationPermission` action.
 *
 * Best practices:
 * https://developers.google.com/web/fundamentals/native-hardware/user-location/
 * @param {Big} timeout - The maximum length of time (in milliseconds) the device is allowed to take in order to return a location. If empty, there is no timeout.
 * @param {Big} maximumAge - The maximum age (in milliseconds) of a possible cached position that is acceptable to return. If set to 0, it means that the device cannot use a cached position and must attempt to retrieve the real current position. By default the device will always return a cached position regardless of its age.
 * @param {boolean} highAccuracy - Use a higher accuracy method to determine the current location. Setting this to false saves battery life.
 * @returns {Promise.<MxObject>}
 */
async function GetCurrentLocation(timeout, maximumAge, highAccuracy) {
    // BEGIN USER CODE
    var _a;
    const isReactNative = navigator && navigator.product === "ReactNative";
    const isWeb = navigator && navigator.geolocation;
    if (!isReactNative && !isWeb) {
        return Promise.reject(new Error("Geolocation module could not be found"));
    }
    // We keep a manual web branch (backed by `navigator.geolocation`) rather than relying on the
    // library's web entry, because it is not guaranteed that the Mendix web client resolves the
    // package's `browser`/`exports` condition. If that is ever confirmed, this branch can be dropped.
    const options = buildLocationOptions(timeout, maximumAge, highAccuracy);
    try {
        let position;
        if (isReactNative) {
            position = await getCurrentPosition(options);
        }
        else {
            position = await new Promise((resolve, reject) => {
                navigator.geolocation.getCurrentPosition(pos => resolve(normalizeWebPosition(pos)), err => reject(err), {
                    timeout: options.timeout,
                    maximumAge: options.maximumAge,
                    enableHighAccuracy: highAccuracy !== null && highAccuracy !== void 0 ? highAccuracy : false
                });
            });
        }
        return new Promise((resolve, reject) => {
            mx.data.create({
                entity: "NanoflowCommons.Geolocation",
                callback: mxObject => {
                    resolve(mapPositionToMxObject(mxObject, position));
                },
                error: () => reject(new Error("Could not create 'NanoflowCommons.Geolocation' object to store location"))
            });
        });
    }
    catch (error) {
        const message = (_a = error === null || error === undefined ? undefined : error.message) !== null && _a !== undefined ? _a : String(error);
        return Promise.reject(new Error(`Could not get current location: ${message}`));
    }
    function buildLocationOptions(timeout, maximumAge, highAccuracy) {
        let timeoutNumber = timeout ? timeout.toNumber() : undefined;
        const maximumAgeNumber = maximumAge ? maximumAge.toNumber() : undefined;
        // If the timeout is 0 or undefined (empty), it causes a crash on iOS.
        // If the timeout is undefined (empty); we set timeout to 30 sec (default timeout)
        // If the timeout is 0; we set timeout to 1 hour (no timeout)
        if (isReactNative && require("react-native").Platform.OS === "ios") {
            if (timeoutNumber === undefined) {
                timeoutNumber = 30000;
            }
            else if (timeoutNumber === 0) {
                timeoutNumber = 3600000;
            }
        }
        return {
            timeout: timeoutNumber,
            maximumAge: maximumAgeNumber,
            accuracy: highAccuracy ? { android: "high", ios: "best" } : { android: "balanced", ios: "hundredMeters" }
        };
    }
    // NOTE: `normalizeWebPosition` is duplicated verbatim in `GetCurrentLocationMinimumAccuracy.ts`.
    // The Mendix action model does not allow sharing code across action files, so if you change this
    // function, keep the copy in the other action in sync.
    function normalizeWebPosition(pos) {
        var _a, _b, _c, _d;
        return {
            coords: {
                latitude: pos.coords.latitude,
                longitude: pos.coords.longitude,
                altitude: (_a = pos.coords.altitude) !== null && _a !== undefined ? _a : null,
                accuracy: pos.coords.accuracy,
                altitudeAccuracy: (_b = pos.coords.altitudeAccuracy) !== null && _b !== undefined ? _b : null,
                heading: (_c = pos.coords.heading) !== null && _c !== undefined ? _c : null,
                speed: (_d = pos.coords.speed) !== null && _d !== undefined ? _d : null
            },
            timestamp: pos.timestamp
        };
    }
    function mapPositionToMxObject(mxObject, pos) {
        mxObject.set("Timestamp", new Date(pos.timestamp));
        mxObject.set("Latitude", new Big(pos.coords.latitude.toFixed(8)));
        mxObject.set("Longitude", new Big(pos.coords.longitude.toFixed(8)));
        mxObject.set("Accuracy", new Big(pos.coords.accuracy.toFixed(8)));
        if (pos.coords.altitude != null) {
            mxObject.set("Altitude", new Big(pos.coords.altitude.toFixed(8)));
        }
        if (pos.coords.altitudeAccuracy != null && pos.coords.altitudeAccuracy !== -1) {
            mxObject.set("AltitudeAccuracy", new Big(pos.coords.altitudeAccuracy.toFixed(8)));
        }
        if (pos.coords.heading != null && pos.coords.heading !== -1) {
            mxObject.set("Heading", new Big(pos.coords.heading.toFixed(8)));
        }
        if (pos.coords.speed != null && pos.coords.speed !== -1) {
            mxObject.set("Speed", new Big(pos.coords.speed.toFixed(8)));
        }
        return mxObject;
    }
    // END USER CODE
}

export { GetCurrentLocation };
