// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} attributeName
 * @param {MxObject} singleObject
 * @returns {Promise.<boolean>}
 */
export async function LocalStorageStoreAttribute(attributeName, singleObject) {
	// BEGIN USER CODE
    if (!singleObject) {
        return false;
    }

    if (!attributeName) {
        throw new TypeError("Input parameter 'Attribute name' is required");
    }

    if (!singleObject.has(attributeName)) {
        const entity = singleObject.getEntity();
        throw new TypeError(`Entity '${entity}' does not have an attribute named '${attributeName}'`);
    }

    const AsyncStorage = require("react-native").AsyncStorage;
    const storeName = `${singleObject.getEntity()}.${attributeName}`;

    return AsyncStorage.getItem(storeName)
        .then(store => {
            const storedValue = store ? JSON.parse(store) : {};
            storedValue[singleObject.getGuid()] = singleObject.get(attributeName);
            return AsyncStorage.setItem(storeName, JSON.stringify(storedValue));
        })
        .then(() => true);
	// END USER CODE
}
