import ReactNativeBiometrics from 'react-native-biometrics';

// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * @param {string} reason - The reason for requesting authentication. If empty, the system default message is used.
 * @returns {Promise.<boolean>}
 */
async function BiometricAuthentication(reason) {
    // BEGIN USER CODE
    // Documentation https://github.com/smallcase/react-native-simple-biometrics
    const rnBiometrics = new ReactNativeBiometrics();
    return rnBiometrics
        .simplePrompt({ promptMessage: reason !== null && reason !== void 0 ? reason : "" })
        .then(() => true)
        .catch(() => false);
    // END USER CODE
}

export { BiometricAuthentication };
