import { NativeModules } from 'react-native';
import notifee from '@notifee/react-native';

// This file was generated by Mendix Studio Pro.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * Cancels all pending scheduled notifications.
 * @returns {Promise.<void>}
 */
async function CancelAllScheduledNotifications() {
    // BEGIN USER CODE
    // Documentation https://github.com/invertase/notifee
    if (NativeModules && !NativeModules.NotifeeApiModule) {
        return Promise.reject(new Error("Notifee native module is not available in your app"));
    }
    notifee.cancelAllNotifications();
    return Promise.resolve();
    // END USER CODE
}

export { CancelAllScheduledNotifications };
