import { NativeModules } from 'react-native';
import notifee from '@notifee/react-native';

// This file was generated by Mendix Studio Pro.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * @param {string} notificationId - This field is required.
 * @returns {Promise.<void>}
 */
async function CancelScheduledNotification(notificationId) {
    // BEGIN USER CODE
    // Documentation Documentation https://github.com/invertase/notifee
    if (NativeModules && !NativeModules.NotifeeApiModule) {
        return Promise.reject(new Error("Notifee native module is not available in your app"));
    }
    if (!notificationId) {
        return Promise.reject(new Error("Input parameter 'Notification id' is required"));
    }
    notifee.cancelNotification(notificationId);
    return Promise.resolve();
    // END USER CODE
}

export { CancelScheduledNotification };
