// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import fetchBlob from 'rn-fetch-blob';
import { Platform } from 'react-native';

// BEGIN EXTRA CODE
function formatPath(...pathArgs) {
    return pathArgs.filter(arg => !!arg).join("/");
}
function sanitizeFileName(name) {
    return name.replace(/[<>"?:|*\/\\\u0000-\u001F\u007F]/g, "_");
}
// END EXTRA CODE

/**
 * @param {string} fileURL - This field is required
 * @param {string} filePath - optional
 * @param {string} fileName - optional - should be with the file extention
 * @returns {Promise.<boolean>}
 */
export async function DownloadFileByURL(fileURL, filePath, fileName) {
	// BEGIN USER CODE
    if (!fileURL) {
        return Promise.reject(new Error("Input parameter 'file URL' is required"));
    }
    const dirs = fetchBlob.fs.dirs;
    try {
        const fileNameOverride = fileName || decodeURIComponent(fileURL.substring(fileURL.lastIndexOf("/") + 1));
        const sanitizedFileName = sanitizeFileName(fileNameOverride);
        const baseDir = Platform.OS === 'ios' ? dirs.DocumentDir : dirs.DownloadDir;
        await fetchBlob
            .config({
            path: formatPath(baseDir, filePath, sanitizedFileName)
        })
            .fetch("GET", fileURL);
        return Promise.resolve(true);
    }
    catch (err) {
        console.error("error", err);
        return Promise.resolve(false);
    }
	// END USER CODE
}
