import ReactNativeBiometrics from 'react-native-biometrics';

// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * @returns {Promise.<boolean>}
 */
async function IsBiometricAuthenticationSupported() {
    // BEGIN USER CODE
    // Documentation https://github.com/smallcase/react-native-simple-biometrics
    const rnBiometrics = new ReactNativeBiometrics();
    return rnBiometrics
        .isSensorAvailable()
        .then(result => result.available)
        .catch(() => false);
    // END USER CODE
}

export { IsBiometricAuthenticationSupported };
