import { fetch } from '@react-native-community/netinfo';

// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * @returns {Promise.<boolean>}
 */
async function IsConnected() {
    // BEGIN USER CODE
    return fetch().then((info) => info.isConnected);
    // END USER CODE
}

export { IsConnected };
