// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Date} date - The calendar app opens at the given date. Set to empty to open today.
 * @returns {Promise.<boolean>}
 */
export async function OpenCalendar(date) {
	// BEGIN USER CODE
  // Documentation: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin
  if (!window.plugins || !window.plugins.calendar) {
    throw new Error("cordova-plugin-calendar not enabled");
  }
  window.plugins.calendar.openCalendar(date || new Date(), function () {
    // This success callback is not called at all
  }, function (error) {
    throw new Error("Failed to open calendar: " + error);
  });
  return Promise.resolve(true);
	// END USER CODE
}
