// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function ScanBarcode() {
	// BEGIN USER CODE
  // Documentation https://github.com/phonegap/phonegap-plugin-barcodescanner
  return new Promise(function (resolve, reject) {
    if (!window.cordova || !window.cordova.plugins || !window.cordova.plugins.barcodeScanner) {
      return reject(new Error("phonegap-plugin-barcodescanner not enabled"));
    }
    window.cordova.plugins.barcodeScanner.scan(function (result) {return resolve(!result.cancelled && result.text && result.text.length > 0 ? result.text : undefined);}, function (error) {return reject(error);});
  });
	// END USER CODE
}
